# Generated by Django 2.2.2 on 2019-06-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='modified_img',
            field=models.ImageField(default='', upload_to='img'),
            preserve_default=False,
        ),
    ]
