# Generated by Django 2.2.2 on 2019-06-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_picture_modified_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='modified_img',
            field=models.ImageField(blank=True, editable=False, upload_to='img'),
        ),
    ]
