# Generated by Django 2.2.2 on 2019-06-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190629_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='image',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='modified_img',
        ),
    ]
