# Generated by Django 2.2.2 on 2019-06-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_picture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='modified_img',
            field=models.ImageField(blank=True, editable=False, upload_to='img'),
        ),
    ]
