# Generated by Django 2.2.2 on 2019-06-29 11:17

from django.db import migrations, models
import functools
import main.generic


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_picture_modified_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=functools.partial(main.generic._update_filename, *(), **{'path': 'dupa.png'})),
        ),
    ]
